Copy the contents of requirements_all_ds.txt into requirements.txt
Also update httplib2 to version 0.15.0, as 0.14.0 is apparently too
old.

When trying this out from the command line on my local Ubuntu 20.04
system, pip installs most of them but throws these errors:

  ERROR: boto3 1.14.63 has requirement botocore<1.18.0,>=1.17.63, but you'll have botocore 1.13.50 which is incompatible.
  ERROR: dql 0.6.2 has requirement botocore>=1.17.55, but you'll have botocore 1.13.50 which is incompatible.
  ERROR: dql 0.6.2 has requirement pyparsing==2.1.4, but you'll have pyparsing 2.3.0 which is incompatible.
  ERROR: snowflake-connector-python 3.0.2 has requirement charset-normalizer<3,>=2, but you'll have charset-normalizer 3.1.0 which is incompatible.
  ERROR: snowflake-connector-python 3.0.2 has requirement cryptography<41.0.0,>=3.1.0, but you'll have cryptography 2.8 which is incompatible.
  ERROR: firebolt-sdk 0.16.2 has requirement cryptography>=3.4.0, but you'll have cryptography 2.8 which is incompatible.
  ERROR: firebolt-sdk 0.16.2 has requirement python-dateutil>=2.8.2, but you'll have python-dateutil 2.8.0 which is incompatible.
  ERROR: firebolt-sdk 0.16.2 has requirement sqlparse>=0.4.2, but you'll have sqlparse 0.3.0 which is incompatible.
  ERROR: pinotdb 0.5.0 has requirement httpx<0.24.0,>=0.23.0, but you'll have httpx 0.24.0 which is incompatible.

We may need to drop those data sources in the short term to get things
to a fully working state, then come back to them at some later point.